---
- name: install wordpress packages
  with_items: "{{ wordpress_packages }}"
  package:
    name: "{{ item.name }}"
  notify:
    - restart php fpm

- name: configure php-fpm
  template:
    src: www.conf.j2
    dest: /usr/local/etc/php-fpm.d/www.conf
  notify:
    - restart php-fpm

- name: enable php fpm
  template:
    src: php_fpm.j2
    dest: /etc/rc.conf.d/php_fpm
  notify:
    - restart php-fpm

- name: copy generate_config script
  copy:
    src: generate_config.sh
    dest: /usr/local/bin/generate_config.sh
    mode: 0700

- name: set permissions
  with_items: "{{ wordpress_dirs }}"
  file:
    path: "/usr/local/www/wordpress{{ item.name }}"
    owner: www
    group: www
    mode: 0755
